version: 2
jobs:
  build:
    working_directory: ~/repo         # my repo

    docker:
      - image: circleci/python:3.7    # primary container for the build job
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd


    steps:
      - checkout # Checkout the repo
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install My-SQL Client
          command: |
            sudo apt-get install default-mysql-client
      - run:
          name: Load the data
          command: |
            mysql -h 127.0.0.1 -u user -ppassw0rd test_db < data.sql

      - run:
          name: Installing Unix- developmemt header files
          command: |
            sudo apt-get install unixodbc unixodbc-dev
      - run:
          name: Installing python3-dev header files
          command: |
            sudo apt-get update -y
            sudo apt-get install -y python3.7-dev
            sudo apt-get install -y libevent-dev

      - run:  # Create virtual env and install dependencies
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt